### ISSUE TITLE
Mermaid diagram rendering support is missing in our website

### ISSUE THREAD

**Issue by VishwasSomasekhariah** [intelops/website#89]
ref - https://raw.githubusercontent.com/intelops/ebpf-experiments/main/network/Example%20XDP/README.md

Github supports mermaid code to render the mermaid code into a diagram for the markdown document. We need the same functionality on our website.

https://github.com/intelops/ebpf-experiments/blob/main/network/Example%20XDP/README.md#architecture-of-library
If you look at this part of the readme file in this above link, the diagram you are seeing is from mermaid code. To see the code you can view the raw readme.

another ref [here](https://navendu.me/posts/adding-diagrams-to-your-hugo-blog-with-mermaid/) 

@tfsojon

**Comment by devopstoday11** [comment]
@tfsojon , this issue is breaking our technical blogs. When we add flow diagrams using the mermaid diagram markdown style in the markdown files, the diagrams are not showing up on our Hugo website. Hence the blog is becoming meaningless without those diagrams. Please add mermaid diagram support for markdown in our Hugo sites (both website and docs site).

**Comment by devopstoday11** [comment]
@VishwasSomasekhariah @AnamikaSanjay 
mermaid support is working now on my chandu branch. After I merge it to main branch, everybody will be able to use that feature in your blogs. 
Thank you @tfsojon
